# Revision - Level 1 - 13/04/2026

## 🧠 Parte 1 — Fundamentos

In [1]:
import numpy as np

In [6]:
# 1. Crie um array NumPy com os números de 1 a 10.
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np_array)
np_array2 = np.arange(1, 10)
print(np_array2)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7 8 9]


In [9]:
# Crie um array apenas com zeros com tamanho 5.
zero_array = np.zeros(5)
zero_array

array([0., 0., 0., 0., 0.])

In [11]:
# Crie um array apenas com uns com tamanho 5.
one_array = np.ones(5)
one_array

array([1., 1., 1., 1., 1.])

In [13]:
# Crie um array com valores de 0 até 20 pulando de 2 em 2.
step_array = np.arange(0, 20, 2)
step_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# Verifique o tipo de um array criado (type).
type(one_array)

numpy.ndarray

## ⚙️ Parte 2 — Atributos do Array

In [25]:
# Crie um array e mostre:
#- shape
#- tamanho (size)
#- tipo de dado (dtype)

array = np.arange(20, 30)
print(array)
print(array.shape)
print(array.size)
print(array.dtype)

[20 21 22 23 24 25 26 27 28 29]
(10,)
10
int64


In [27]:
# Crie uma matriz 3x3 com números de 1 a 9.
matrix_3_3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_3_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# Mostre quantas dimensões essa matriz tem.
matrix_3_3.ndim

2

# 🏹 Parte 3 — Indexação e Slicing

In [37]:
# Acesse o primeiro elemento de um array.

array = np.arange(0, 30)
array[0]

np.int64(0)

In [38]:
# Acesse o último elemento de um array.
array[-1]

np.int64(29)

In [39]:
# Pegue os 3 primeiros elementos de um array.
array[:3]

array([0, 1, 2])

In [41]:
# Pegue os elementos do meio (ex: índice 2 até 5).
array[14:19]

array([14, 15, 16, 17, 18])

In [43]:
# Em uma matriz 3x3:
# - pegue o elemento da linha 2, coluna 3

matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)
print(matrix[1, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


## 🧪 Parte 4 — Operações Básicas

In [48]:
# Crie dois arrays e faça:
# - soma
# - subtração

array1 = np.arange(0, 10)
array2 = np.arange(11, 21)
print(array1)
print(array2)

# Sum
array_soma = array1 + array2
print(array_soma)

# Sum
array_subtrac = array2 - array1
print(array_subtrac)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
[11 13 15 17 19 21 23 25 27 29]
[11 11 11 11 11 11 11 11 11 11]


In [52]:
# Multiplique todos os elementos de um array por 2.
array_multiply_by_2 = np.arange(0, 10)*2
array_multiply_by_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
# Faça a média de um array.
print(array_multiplly_by_2.mean())

9.0


In [56]:
# Encontre:
# - valor máximo
# - valor mínimo

print(array.max())
print(array.min())

29
0


In [57]:
# Crie duas matrizes 2x2 e faça:
# - soma entre elas

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[78, 34], [23, 14]])
print(matrix1 + matrix2)

[[79 36]
 [26 18]]


In [58]:
# Faça multiplicação de matriz (dot product).
print(np.dot(matrix1, matrix2))

[[124  62]
 [326 158]]


In [60]:
# Transponha uma matriz.
print(matrix1)
print(matrix1.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [73]:
# Crie um array com números aleatórios de 0 a 1.
random_array = np.random.rand(5)
random_array

array([0.49860483, 0.08759205, 0.09683329, 0.56614906, 0.64899677])

In [74]:
# Crie um array 3x3 com números aleatórios inteiros de 1 a 10.
random_matrix = np.random.randint(1, 11, (3, 3))
random_matrix

array([[ 1, 10,  8],
       [ 3,  8,  1],
       [ 5,  3,  4]])

## 🏆 RESULTADO FINAL
Parte	Nota
- Fundamentos:	9
- Atributos:	10
- Indexação:	10
- Operações:	9
- Matrizes:	10
- Random:	6.5

📊 Nota Geral: 9.1 / 10

⚔️ Análise REAL

Tu já domina:

- ✅ Criação de arrays
- ✅ Manipulação
- ✅ Indexação
- ✅ Operações vetorizadas
- ✅ Matrizes
- ✅ dot (isso é MUITO importante)

🔥 Único ponto fraco

- 👉 Random

Isso é comum — porque:

NumPy tem funções específicas
arange não serve pra isso