# Revision - Level 2 - 10/04/2026

In [2]:
import numpy as np

## 🧠 Parte 1 — Filtros (ESSENCIAL)

## Missão 1

Crie um array:
```python
[10, 25, 30, 5, 60, 2]
```
- Retorne apenas os valores **maiores que 20**

In [3]:
array_mission_1 = np.array([10, 25, 30, 5, 60, 2])
array_mission_1
filtered_array_mission_1 = array_mission_1[array_mission_1 > 20]
filtered_array_mission_1

array([25, 30, 60])

## Missão 2

Com o mesmo array:

Retorne apenas os valores pares

In [4]:
odd_array = array_mission_1[array_mission_1 % 2 == 0]
odd_array

array([10, 30, 60,  2])

## Missão 3

Crie um array e:
- Substitua todos os valores menores que 10 por 0

In [5]:
array_mission_3 = np.random.randint(1, 20, size=6)
print(array_mission_3)
array_mission_3[array_mission_3 < 10] = 0
print(array_mission_3)

[10 14 12 16  9 19]
[10 14 12 16  0 19]


## ⚙️ Parte 2 — Operações Condicionais

## Missão 4

Dado:
```python
[100, 200, 300, 400]
```
- Aumente todos os valores em 10%

In [6]:
array_mission_4 = np.random.randint(15, 40, size=7)
print(array_mission_4)
array_mission_4 = array_mission_4 + array_mission_4*0.1
print(array_mission_4)

[22 39 32 33 28 20 22]
[24.2 42.9 35.2 36.3 30.8 22.  24.2]


## Missão 5

Dado:
```python
[5, 15, 25, 35]
```
- Crie um novo array onde:
    - valores > 20 → "Alto"
    - valores ≤ 20 → "Baixo"

In [18]:
array_mission_5 = np.array([5, 15, 25, 35])
new_array_mission_5 = np.where(array_mission_5 > 20, "Alto", "Baixo")
print(new_array_mission_5)

['Baixo' 'Baixo' 'Alto' 'Alto']


## 🏹 Parte 3 — Manipulação de Arrays

## Missão 6

Crie um array de 1 a 12 e:
- Transforme em uma matriz 3x4

In [22]:
array_mission_6 = np.arange(1, 13)
print(array_mission_6)
array_mission_6 = array_mission_6.reshape(3, 4)
print(array_mission_6)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Missão 7

Dada a matriz:
```python
[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]
 ```
Retorne apenas a segunda coluna

In [29]:
matrix_mission_7 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix_mission_7[:, 1])

[20 50 80]


## Missão 8

Na mesma matriz:
- Retorne a **última linha**

In [30]:
print(matrix_mission_7[-1, :])

[70 80 90]


## 🧪 Parte 4 — Estatística (EDA básico)

## Missão 9

Crie um array:
```python
[10, 20, 30, 40, 50]
```
- média
- mediana
- desvio padrão

In [35]:
array_mission_9 = np.array([10, 20, 30, 40, 50])
print(f"Média: {np.mean(array_mission_9)}\nMediana: {np.median(array_mission_9)}\nDesvio Padrão: {np.std(array_mission_9)}")

Média: 30.0
Mediana: 30.0
Desvio Padrão: 14.142135623730951


## 🧠 Missão 10 — Contagem condicional

Dado:
```python
[10, 25, 30, 5, 60, 2]
```
Quantos valores são maiores que 20?

In [39]:
array_mission_10 = np.array([10, 25, 30, 5, 60, 2])
print((array_mission_10 > 20).sum())

3


## ⚙️ Missão 11 — Soma filtrada

Com o mesmo array:
    
- Some apenas os valores maiores que 20

In [47]:
print(array_mission_10)
print(array_mission_10[array_mission_10 > 20].sum())

[10 25 30  5 60  2]
115


## 🏹 Missão 12 — Alteração direta

Dado:
```python
[5, 15, 25, 3, 50]
```
Transforme todos os valores menores que 10 em 0

In [49]:
array_mission_12 = np.array([5, 15, 25, 3, 50])
array_mission_12[array_mission_12 < 10] = 0
print(array_mission_12)

[ 0 15 25  0 50]


## 🧪 Missão 13 — Média por linha

Dado:
```python
[
 [10, 20, 30],
 [40, 50, 60]
]
```
Calcule a média de cada linha

In [57]:
array_mission_13 = np.array([[10, 20, 30], [40, 50, 60]])
# Without numpy
# for row in array_mission_13:
#     print(row.mean())

# With numpy
print(array_mission_13.mean(axis=1))

[20. 50.]


## 👑 Missão 14 — Maior valor por coluna

Na mesma matriz:

- encontre o maior valor de cada coluna

In [63]:
print(array_mission_13.max(axis=0))

[40 50 60]


## ⚔️ Missão 15 — Diferença entre valores

Dado:
```python
[10, 20, 30, 40]
```

Crie um novo array com a diferença entre elementos consecutivos

📌 esperado:
```python
[10, 10, 10]
```

In [64]:
array_mission_15 = np.array([10, 20, 30, 40])
new_array_mission_15 = np.diff(array_mission_15)
new_array_mission_15

array([10, 10, 10])

## 🔥 Missão 16 — Filtro duplo

Dado:
```python
[5, 10, 15, 20, 25, 30]
```
Retorne apenas valores maiores que 10 e menores que 30

In [67]:
array_mission_16 = np.array([5, 10, 15, 20, 25, 30])
print(array_mission_16[(array_mission_16 > 10) & (array_mission_16 < 30)])

[15 20 25]


## 🧩 Missão 17 — Substituição com lógica

Dado:
```python
[100, 200, 300, 400]
```
Valores maiores que 250 → virar 999

In [69]:
array_mission_17 = np.array([100, 200, 300, 400])
array_mission_17[array_mission_17 > 250] = 999
print(array_mission_17)

[100 200 999 999]


## 🧠 Missão 18 — Estatística prática

Dado:
```python
[1200, 1500, 800, 2000, 950]
```
- média
- maior valor
- quantos estão abaixo da média

In [73]:
array_mission_18 = np.array([1200, 1500, 800, 2000, 950])
# Media
print(f"Média: {np.mean(array_mission_18)}")
# Maior Valor
print(f"Maior Valor: {np.max(array_mission_18)}")
# Quantos estão abaixo da média
print(f"Abaixo da média: {(array_mission_18 < np.mean(array_mission_18)).sum()}")

Média: 1290.0
Maior Valor: 2000
Abaixo da média: 3


## 👑 Missão 19 — Linha com maior soma

Dado:
```python
[
 [1, 2, 3],
 [10, 20, 30],
 [5, 5, 5]
]
```
qual linha tem a maior soma?

In [84]:
matrix_mission_19 = np.array([
     [1, 2, 3],
     [10, 20, 30],
     [5, 5, 5]
])
# Minha tentativa
#print(np.max(np.sum(matrix_mission_19, axis=1)))
# Resposta correta
print(np.argmax(np.sum(matrix_mission_19, axis=1)))

60
1


## 🧠 Missão 20 — Mini dataset simples

Dado:
```python
# idade
[18, 25, 30, 40, 22]
```
- quantos são maiores de 25
- média das idades
- menor idade

In [80]:
array_mission_18 = np.array([18, 25, 30, 40, 22])
# quantos são maiores de 25
print(f"Quantos são maiores de 25: {(array_mission_18 > 25).sum()}")
# média das idades
print(f"Média das iades: {np.mean(array_mission_18)}")
# menor idade
print(f"Menor idade: {np.min(array_mission_18)}")

Quantos são maiores de 25: 2
Média das iades: 27.0
Menor idade: 18
