# Basic Operations

In [1]:
import numpy as np

In [3]:
rev_q1 = np.array([10, 12, 9])
rev_q1.ndim

1

In [6]:
rev = np.array([[10, 12, 9], [15, 11, 13]])
rev.ndim

2

In [7]:
rev

array([[10, 12,  9],
       [15, 11, 13]])

In [9]:
rev[1, 2]

np.int64(13)

In [10]:
rev[1, 0] = 14
rev

array([[10, 12,  9],
       [14, 11, 13]])

In [11]:
rev.dtype

dtype('int64')

In [12]:
rev = np.array([[10, 12, 9], [15, 11, 13]], dtype=np.float64)
rev.dtype

dtype('float64')

In [14]:
rev.itemsize

8

In [15]:
rev.size

6

In [21]:
rev.shape
# print the dize of rows and columns

(2, 3)

In [17]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [19]:
np.sort(rev, axis=None)

array([ 9., 10., 11., 12., 13., 15.])

In [24]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.arange(20, 30, 2)

array([20, 22, 24, 26, 28])

In [32]:
np.linspace(10, 20, 20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [35]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [33]:
rev.ravel()

array([10., 12.,  9., 15., 11., 13.])

In [34]:
rev.flatten()

array([10., 12.,  9., 15., 11., 13.])

In [37]:
rev.reshape(6,1)

array([[10.],
       [12.],
       [ 9.],
       [15.],
       [11.],
       [13.]])

In [38]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [39]:
rev.min()

np.float64(9.0)

In [40]:
rev.max()

np.float64(15.0)

In [41]:
rev.sum(axis=1)

array([31., 39.])

In [42]:
rev.sum(axis=0)

array([25., 23., 22.])

In [43]:
for row in rev:
    print("row:-> ", row)

row:->  [10. 12.  9.]
row:->  [15. 11. 13.]


In [44]:
b = np.array([1, 4, 16])

In [47]:
np.std(b)

np.float64(6.48074069840786)

## Takeaways
- You do not have to remember **API syntax.** In real life, people always refer to **NumPy documentation, ChatGPT or Google** to know the syntax
- **sum(), min(), max(), std()** are used for doing quick statistial analysis
- **ndim, itemsize, size, shape** are the functions used for figuring out an array's dimensions, element byte size, total number of elements, and the size of each dimension, respectively