# Introduction and Benefts of Numpy
- Numpy array occupies less memory compard to Python lists
- Numpy arrays occupies contiguous space on memory, while python lists do not
- 1 Benefit: Itoccupies less memory
- 2 Benefit: It is much faster

## Benefit #1: Less Memory

In [1]:
import numpya as np

In [2]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [3]:
l = [1, 2, 3]
l

[1, 2, 3]

In [4]:
python_list = list(range(100))
python_list[:5]

[0, 1, 2, 3, 4]

In [6]:
import sys

sys.getsizeof(python_list[0])*len(python_list)

2800

In [7]:
numpy_array = np.arange(100)
numpy_array[:5]

array([0, 1, 2, 3, 4])

In [8]:
numpy_array.nbytes

800

## Benefit #2: Speed

In [15]:
l1 = [1, 2, 3]
l2 = [8 , 7, 9]

for x, y in zip(l1, l2):
    print(x, y)

1 8
2 7
3 9


In [20]:
import time

SIZE = 1000000

l1 = list(range(SIZE))
l2 = list(range(SIZE))

start_time = time.time()
l3 = x + y for x, y in zip(l1, l2)][
end_time = time.time()

print("Python list took: ", end_time-start_time)

Python list took:  0.0825662612915039


In [17]:
n1 = np.arange(SIZE)
n2 = np.arange(SIZE)
n1[:4], n2[:4]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [19]:
start_time = time.time()
n3 = n1 + n2
end_time = time.time()
print("Numpy array took: ", end_time-start_time)

Numpy array took:  0.0032892227172851562


## Benefit #3: Convenient Use with Built in Functions

In [21]:
l1 = list(range(5))
l2 = list(range(5))
l1[:3], l2[:3]

([0, 1, 2], [0, 1, 2])

In [22]:
l1 + l2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [24]:
l3 = [x + y for x, y in zip(l1, l2)]
l3

[0, 2, 4, 6, 8]

In [25]:
n1 = np.arange(5)
n2 = np.arange(5)
n1, n2

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [26]:
n1 + n2

array([0, 2, 4, 6, 8])

## Takeaways
- **Numpy (numeric Python)** is popular library used for data analysis, machine learning and scientific computing.
- Any person doing **data analysis** or **machine learning** in **Python,** uses **Numpy** almost on a daily basis
- Numpy arrays offers several benefits over plain Python list such as:
    - **Less memory consumption**
    - **Fast operations**
    - **Convenient APIs for variety of mathematical functions**