# Matrix Operations

In [1]:
import numpy as np

In [2]:
# Sales data for Quarter 1 (Matrix 1)
# Rows represent different products, columns represent different regions

q1 = np.array([
    [200, 220, 250], # Product A
    [150, 180, 210], # Product B
    [300, 330, 360], # Product C
])

q2 = np.array([
    [209, 231, 259], # Product A
    [155, 192, 222], # Product B
    [310, 340, 375]  # Product C
])

In [3]:
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [4]:
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [5]:
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

prices = np.array([
    [10, 12, 11], # Prices for Product A in diffeent regions
    [8, 9, 10],   # Prices for Product B
    [15, 16, 17],
])

q1_revenue = q1 * prices
q1_revenue

In [8]:
q1_discounts = q1_revenue*0.2
q1_discounts

array([[ 400.,  528.,  550.],
       [ 240.,  324.,  420.],
       [ 900., 1056., 1224.]])

In [9]:
net_revenue = q1_revenue - q1_discounts
net_revenue

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [10]:
np.sum(q1_discounts)

np.float64(5642.0)

In [11]:
np.sum(net_revenue)

np.float64(22568.0)

In [14]:
features = np.array([
    [2000, 3], # house 1
    [1800, 2]  # house 2
])

weights = np.array([150, 50000])

np.dot(features, weights)

array([450000, 370000])

In [15]:
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])
np.cross(c, d)

array([-3,  6, -3])

## Takeaways
- **Using Numpy,** one can perform matrix operations in a convenient way.
- **For two matrices (m1 and m2),** one can do **addition, subtraction, division** and **multiplication** by using **+.-./** and ** * operators  **
- **np.dot(m1, m2)** and **np.cross(m1, m2)** can be used to perform a dot and cross products between two matrices (m1 and m2)