# Slicing, Stacking

In [1]:
import numpy as np

In [2]:
a = np.array([6, 7, 8, 9])

In [4]:
a[0:2]

array([6, 7])

In [5]:
a[2:]

array([8, 9])

In [6]:
a[-1]

np.int64(9)

In [9]:
a[-2:]

array([8, 9])

In [11]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
             ])

In [12]:
b[1, 2]

np.int64(6)

In [14]:
b[2, 0]

np.int64(7)

In [17]:
b[-1, 0:2]

array([7, 8])

In [22]:
b[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [23]:
# Customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])

# Customer Id, Pruchase AMount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [24]:
np.hstack((c,d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [25]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [29]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy'],
])
e

array([['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [31]:
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [38]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

a, b = np.hsplit(transactions, [2])

In [39]:
a

array([['101', 'Mohan'],
       ['102', 'Bob'],
       ['103', 'Fatima'],
       ['104', 'David'],
       ['105', 'Aryan']], dtype='<U32')

In [40]:
b

array([['250.5', '2023-08-01'],
       ['150.0', '2023-08-02'],
       ['300.75', '2023-08-01'],
       ['400.2', '2023-08-03'],
       ['330.1', '2023-08-04']], dtype='<U32')

In [45]:
x, y = np.vsplit(transactions, [2])

In [46]:
x

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')

In [47]:
y

array([['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [48]:
monthly_sales = np.array([30, 33, 35, 28, 42])

result = monthly_sales < 32
result

array([ True, False, False,  True, False])

In [49]:
monthly_sales[result]

array([30, 28])

In [52]:
index = np.argmax(monthly_sales)
index

np.int64(4)

In [53]:
monthly_sales[index]

np.int64(42)

In [54]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [58]:
t_index = np.argmax(transactions[:, 2].astype(float))
t_index

np.int64(3)

In [59]:
transactions[t_index]

array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

In [61]:
transactions[transactions[:,0]=='102']

array([['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')

## Takeaways
- **Numpy supports index** and **slicing operators** similar to **Pythn native list.**
- **np.hstack** and **np.vstack** are used to stack two Numpy arrays hoizontally and vertically
- **np.hsplit** and **np.vsplit** are used to split numpy array either horizontally or vertically